[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "qa-engineering-lab"
version = "0.1.0"
description = "QA Automation Framework"
requires-python = ">=3.14"

[tool.setuptools]
packages = ["framework"]

[tool.pytest.ini_options]
pythonpath = [
    "."
]

testpaths = [
    "tests"
]

python_files = [
    "test_*.py"
]

python_functions = [
    "test_*"
]

addopts = [
    "-v"
]

[tool.ruff]
line-length = 88
target-version = "py314"

exclude = [
    ".git",
    ".venv",
    ".pytest_cache",
    "__pycache__",
    "external",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]
